module.exports = {
  user_not_authorised: 'User not authorised',
  post_not_found: 'Could not find post with the id provided',
  posts_not_found: 'No posts found',
  comment_not_found: 'Could not find comment with the id provided',
  text_field_required: 'Text field is required',
  post_invalid_length: 'Post must be between 6 and 300 characters long',
  post_not_yet_liked: 'You have not yet liked this post',
  post_already_liked: 'User has already liked post',
  profile_not_found_for_current_user: 'Profile not found for current user',
  profile_not_found_for_user_id: 'Profile not found for given user id',
  profile_not_found_for_handle: 'Profile not found for given handle',
  profiles_not_found: 'No profiles found',
  profile_not_found_generic: 'No profile found',
  handle_already_exists: 'This handle already exists',
  email_already_taken: 'Email already taken',
  no_user_for_email: 'User does not exist',
  password_not_match: 'Password does not match',
  school_field_required: 'School field is required',
  degree_field_required: 'Degree field is required',
  fieldOfStudy_field_required: 'Field Of Study field is required',
  school_field_required: 'School field is required',
  from_date_field_required: 'From date field is required',
  title_field_required: 'Title field is required',
  company_field_required: 'Company field is required',
  invalid_email: 'Email is invalid',
  email_field_required: 'Email field is required',
  password_field_required: 'Password field is required',
  password_invalid_length: 'Password must be between 6 and 30 characters long',
  confirm_password_field_required: 'Confirm Password field is required',
  passwords_must_match: 'Passwords must be a match',
  name_invalid_length: 'Name must be between 2 and 30 characters long',
  name_field_required: 'Name field is required',
  handle_invalid_length: 'Handle must be between 2 and 40 characters long',
  handle_required: 'Profile handle is required',
  status_required: 'Profile status is required',
  skills_required: 'Profile skills is required',
  invalid_url: 'Not a valid URL'
};